# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houdasfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturegallery',
            name='picture',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
